--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 24/07/2024 00.38.30
-- Server version: 10.4.28
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO mobil.bookings(id, client_id, mobil_id, name, alamat, telepon, mobil, tanggal_keluar, tanggal_masuk, created_at, updated_at, Nomor_plat) VALUES
(5, 1, 2, 'q', 'asdasda', '12312', 'galant', '2024-07-23', '2024-08-26', '2024-07-23 12:25:47', '2024-07-23 12:25:47', '212');




INSERT INTO mobil.clients(id, telepon, no_SIM, alamat, user_id, created_at, updated_at) VALUES
(1, '12312', '1231231', 'asdasda', 2, '2024-07-23 12:20:21', '2024-07-23 12:20:21'),
(2, '87192', '298374', 'kajsda', 3, '2024-07-23 12:20:40', '2024-07-23 12:20:40'),
(3, '083173368211', '34534534', 'jala puma 3 nomer 58 RT 04 RW 01 Kelurahan Sulaiman\r\nhouse', 4, '2024-07-23 13:30:37', '2024-07-23 13:30:37');



INSERT INTO mobil.histories(id, name, alamat, telepon, mobil, plat, tanggal_keluar, tanggal_masuk, status, created_at, updated_at) VALUES
(3, 'q', 'asdasda', '12312', 'sigra', '2357456', '2024-07-23', '2024-07-26', 'keluar', '2024-07-23 12:25:39', '2024-07-23 12:25:39'),
(4, 'q', 'asdasda', '12312', 'galant', '212', '2024-07-23', '2024-08-26', 'keluar', '2024-07-23 12:25:47', '2024-07-23 12:25:47'),
(5, 'q', 'asdasda', '12312', 'sigra', '2357456', '2024-07-23', '2024-07-26', 'masuk', '2024-07-23 12:26:31', '2024-07-23 12:26:31');




INSERT INTO mobil.migrations(id, migration, batch) VALUES
(24, '2024_07_18_025642_add_foto_to_users_table', 3),
(25, '2024_07_18_025750_add_foto_to_mobils_table', 4),
(195, '0001_01_01_000000_create_users_table', 5),
(196, '0001_01_01_000001_create_cache_table', 5),
(197, '0001_01_01_000002_create_jobs_table', 5),
(198, '2024_07_17_102310_create_clients_table', 5),
(199, '2024_07_17_144156_create_mobils_table', 5),
(200, '2024_07_18_030445_add_foto_to_mobils_table', 5),
(201, '2024_07_19_030829_create_bookings_table', 5),
(202, '2024_07_19_065821_add__nomor_plat_to_bookings_table', 5),
(203, '2024_07_19_161756_create_pengembalians_table', 5),
(204, '2024_07_23_064906_add_role_to_users_table', 5),
(205, '2024_07_23_120840_create_histories_table', 5);


INSERT INTO mobil.mobils(id, model, merek, nama_mobil, Nomor_plat, tarif, status, created_at, updated_at, foto) VALUES
(1, 'sedan', 'daihatsu', 'sigra', '2357456', 123412, 1, '2024-07-23 12:21:11', '2024-07-23 12:21:11', 'SON00420.png'),
(2, 'MPV', 'mitsubisho', 'galant', '212', 123123, 0, '2024-07-23 12:21:26', '2024-07-23 12:21:26', 'Screenshot-2023-07-18-135647.png');



INSERT INTO mobil.pengembalians(id, client_id, name, alamat, telepon, mobil, nomor_plat, tanggal_keluar, tanggal_masuk, tarif, status_pengembalian, created_at, updated_at) VALUES
(1, 1, 'q', 'asdasda', '12312', 'sigra', '2357456', '2024-07-23', '2024-07-26', 'Rp 370.236,00', 0, '2024-07-23 12:26:31', '2024-07-23 12:26:31');


INSERT INTO mobil.sessions(id, user_id, ip_address, user_agent, payload, last_activity) VALUES
('DG0XgMK1Su3w6Spc45QcbboI8w1TYAyCRJEOn3KR', 1, '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36', 'YTo0OntzOjY6Il90b2tlbiI7czo0MDoiUndEY0duTURGeTkyOUlkMFhuclYyR0dZOXpOcnJ4Y1NQVWViVWRTMCI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6Mjk6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9oaXN0b3JpIjt9czo1MDoibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO2k6MTt9', 1721747813);


INSERT INTO mobil.users(id, name, email, email_verified_at, password, remember_token, created_at, updated_at, role) VALUES
(1, 'admin', 'admin@admin.com', '2024-07-23 12:19:32', '$2y$12$QvllrxtFucw527EEbC.DSuINepcCoUtW9TgNtQY9BTwwa7kefgXve', 'ByVGcIBdBDGKXMFllmngwjwlYZGnSXbSB9RMliM1CYfRvOb72rkS6iNvrzyp', '2024-07-23 12:19:33', '2024-07-23 12:19:33', 'admin'),
(2, 'q', 'q@q.com', NULL, '$2y$12$LCNUb3PJaEFSFdwmgdeYv.FjWPFwxscYsMFjJw41bBAmCDYpzjm2m', NULL, '2024-07-23 12:20:21', '2024-07-23 12:20:21', 'client'),
(3, 'w', 'w@w.com', NULL, '$2y$12$zD.YJs4Tb.41Gwn.hcpUBulqXxoexGZqSDqig4w9Mu1oyR0.SvXf2', NULL, '2024-07-23 12:20:40', '2024-07-23 12:20:40', 'client'),
(4, 'sandi tyas nugroho', 'Sandytyasn@gmail.com', NULL, '$2y$12$hJSX.yzDsCSpiVGkq5qn6OSG2NgrU.7/HR24AZw8qjikhtqf1rY/e', NULL, '2024-07-23 13:30:37', '2024-07-23 13:30:37', 'client');